baseURL = "https://false.org.ru/"
languageCode = "en-us"
title = "False Protagonist"
author = "Rinat Sabitov"
copyright = "© 2022 by Rinat Sabitov"

canonifyurls = true
theme = "alageek"

#disqusShortname = "false-org-ru"
buildDrafts = true
enableEmoji = true
enableRobotsTXT = false

[pagination]
pagerSize = 20

[params]
enableRSS = true
copyright = "© 2025 by Rinat Sabitov"
copyrightUrl = "https://false.org.ru"

latestpostcount = 3

highlightjs = true
highlightjslanguages = [ "bash", "css", "diff", "django", "javascript", "python", "yaml" ]

description = "I’m a software developer. Proud father of two boys. Infrequent blogger."

[[menu.primary]]
identifier = "code"
name = "Code"
url = "//github.com/histrio"
weight = 10

[[menu.primary]]
identifier = "posts"
name = "Posts"
url = "/blog"
weight = 20

[[menu.primary]]
identifier = "cv"
name = "CV"
url = "/cv"
weight = 30

[[menu.primary]]
identifier = "bmc"
name = "Buy me a coffee"
url = "https://www.buymeacoffee.com/histrio"
weight = 120
